services:
  app:
    image: rina7778/yadro-practical-course:v1.0
    user: "65532:65532"

    read_only: true
    tmpfs:
      - /tmp

    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: "${PORT}"
    restart: unless-stopped