apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: yadro-currency-api-image-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: yadro-currency-api
      images:
        - alias: app
          imageName: rina7778/yadro-practical-course:v1.0.0-8eee60d-20260512213607
          commonUpdateSettings:
            updateStrategy: semver
            forceUpdate: true
            allowTags: "regexp:^v\\d+\\.\\d+\\.\\d+-(?:\\d{14}-[a-f0-9]{7}|[a-f0-9]{7}-\\d{14})$"
            pullSecret: pullsecret:argocd/dockerhub-secret
          manifestTargets:
            helm:
              name: image.repository
              tag: image.tag
  writeBackConfig:
    method: git:secret:argocd/gitlab-image-updater-writeback
    gitConfig:
      repository: https://education-git.yadro.com/education/devops/2026/a.sheynova/app.git
      branch: a.sheynova/main
      writeBackTarget: helmvalues:/k8s-deploy-app/yadro-currency-app/values.yaml
      pullRequest:
        gitlab: {}
