apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yadro-currency-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://education-git.yadro.com/education/devops/2026/a.sheynova/app.git
    path: k8s-deploy-app/yadro-currency-app
    targetRevision: a.sheynova/hw9
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
