upstream k8s_ingress_http {

    least_conn;

    # IP — ноды; порт — второе число из 80:<NodePort>/TCP у ingress-nginx-controller
    server 10.0.0.1:31214 max_fails=3 fail_timeout=10s;
    # server 10.0.0.2:31214 max_fails=3 fail_timeout=10s;

    keepalive 32;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    # server_name api.example.com;

    client_max_body_size 20m;

    location / {
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";

        proxy_connect_timeout 10s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;

        proxy_pass http://k8s_ingress_http;
    }
}
